name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:  # Add manual trigger

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools wheel pybind11 twine

      - name: Build distributions
        run: |
          # Use modern build system
          python -m build --sdist --wheel .
          # Rename wheel with manylinux tag to satisfy PyPI
          find dist -name "*.whl" -exec sh -c 'mv "$0" "${0/-linux_/-manylinux_2_17_}"' {} \;

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment:
      name: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI using twine
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*
