name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:  # Add manual trigger

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools wheel pybind11 twine auditwheel

      - name: Build distributions
        run: |
          # Build source distribution
          python -m build --sdist .
          # Build wheel
          python -m build --wheel .
          # Use auditwheel to repair the wheel with manylinux tag
          auditwheel repair dist/*.whl --plat manylinux_2_17_x86_64 -w dist/
          # Remove the original linux wheel
          rm dist/*-linux_*.whl

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment:
      name: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI using twine
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*
